### ISSUE TITLE
steal script error with new items

### ISSUE THREAD

**Issue by mwest152** [rpherbig/dr-scripts#1151]
Attempting to steal new items for the database returned an error, let me know if I can get you more info:

```
H> shop wall
You come out of hiding.
On the display wall, you see:

  a deobar-handled morning star for 281 copper Kronars
  a steel horseman's axe for 350 copper Kronars
  a beveled broadaxe set on an oak haft for 5 gold Kronars
  a squat iron mace with a rounded head for 312 copper Kronars
  a war mattock with a wide adze for 406 copper Kronars
  a square-faced war hammer with an opposing spike for 306 copper Kronars
  a steel mace covered in claw-shaped flanges for 156 copper Kronars

[Type SHOP [GOOD] to see some details about it.]
> ,steal star wall

--- Lich: steal active.

--- Lich: equipmanager active.

--- Lich: equipmanager has exited.

[steal: This appears to be a new item, send yes  if this is correct, or no to cancel]

> ,send yes

--- sent: yes

[steal]>stow right

You put your mace in your rapier sheath.
> 
[steal]>inv combat

> 
All of your combat:

  a bone-inlaid assassin's bow
  a gold-plated parry stick set with shimmering white diamonds
[Type INVENTORY HELP for more options]
> 
[steal]>sort auto head

Your inventory is now arranged in head-to-toe order.
> 
[steal]>hide

You melt into the background, convinced that your attempt to hide went unobserved.
Roundtime: 2 sec.

HR> 
[steal]>steal star wall

Moving stealthily, you manage to grab a morning star right from underneath a sales clerk's very nose.
You learned exceptionally well from this nearly impossible theft.
A sales clerk points to where you lie concealed and begins to shout loudly for help.
You come out of hiding.
Roundtime: 8 sec.

R> 
--- Lich: error: 757: unexpected token at 'null'
	C:/Ruby200/lib/ruby/2.0.0/json/common.rb:155:in `parse'
	C:/Ruby200/lib/ruby/2.0.0/json/common.rb:155:in `parse'

--- Lich: dependency has exited.

R> ,ka

--- Lich: jail-buddy has exited.

--- Lich: afk has exited.

--- Lich: steal has exited.
```

**Comment by mwest152** [comment]
Not sure where we left off on this, but at 2am EST tried to steal some items in Riverhaven, it i just isnt giving the steal command.  Will buff, remove gear, then just dresses again and unbuffs.
