### ISSUE TITLE
Lich debug is logging every command (GLITCH)

### ISSUE THREAD

**Issue by intangibles** [rpherbig/dr-scripts#1397]
Lich is logging every user command to the debug file for GLITCH.  It does not apply to commands entered via Lich Script.  This behavior does not occur in Stormfront, just Genie client.

```
> 2017-02-20 16:22:10: info: Lich 4.7.23f
> 2017-02-20 16:22:10: info: Ruby 2.0.0
> 2017-02-20 16:22:10: info: i386-mingw32
> 2017-02-20 16:22:10: error: Permission denied - E:/DragonRealms/lich/temp/debug-2017-02-12-13-36-25.log
> 	lich.rbw:10064:in `delete'
> 	lich.rbw:10064:in `block in <main>'
> 	lich.rbw:10062:in `each'
> 	lich.rbw:10062:in `<main>'
> 2017-02-20 16:22:10: info: pretending to be dr.simutronics.net
> 2017-02-20 16:22:10: info: listening on port 11024
> 2017-02-20 16:22:10: info: waiting for the client to connect...
> 2017-02-20 16:22:21: info: connection with the game client is open
> 2017-02-20 16:22:21: info: connecting to the real game host...
> 2017-02-20 16:22:21: info: connection with the game host is open
> 2017-02-20 16:22:21: 
> 2017-02-20 16:22:21: 
> 2017-02-20 16:22:35: <c>asfsfa
> 
> 2017-02-20 16:22:36: <sendSettings/>
> 2017-02-20 16:27:57: <c>,training
> 
> 2017-02-20 16:28:03: <c>,status-email
> 
> 2017-02-20 16:42:04: error: server_thread: malformed XML: missing tag start
> Line: 1
> Position: 108
> Last 80 unconsumed characters:
> <streamWindow id='main' title='Story' subtitle=" - ["Kertigen's Honor"]" location
> 	C:/Ruby200/lib/ruby/2.0.0/rexml/parsers/baseparser.rb:372:in `pull_event'
> 	C:/Ruby200/lib/ruby/2.0.0/rexml/parsers/baseparser.rb:183:in `pull'
> 	C:/Ruby200/lib/ruby/2.0.0/rexml/parsers/streamparser.rb:16:in `parse'
> 	C:/Ruby200/lib/ruby/2.0.0/rexml/document.rb:243:in `parse_stream'
> 	lich.rbw:7164:in `block in open'
> 2017-02-20 16:42:04: error: server_thread: malformed XML: missing tag start
> Line: 1
> Position: 135
> Last 80 unconsumed characters:
> <streamWindow id='room' title='Room' subtitle=" - ["Kertigen's Honor"]" location=
> 	C:/Ruby200/lib/ruby/2.0.0/rexml/parsers/baseparser.rb:372:in `pull_event'
> 	C:/Ruby200/lib/ruby/2.0.0/rexml/parsers/baseparser.rb:183:in `pull'
> 	C:/Ruby200/lib/ruby/2.0.0/rexml/parsers/streamparser.rb:16:in `parse'
> 	C:/Ruby200/lib/ruby/2.0.0/rexml/document.rb:243:in `parse_stream'
> 	lich.rbw:7164:in `block in open'
> 2017-02-20 16:59:54: <c>exp magic
> 
> 2017-02-20 17:00:06: <c>exp magic
> 
> 2017-02-20 17:00:18: <c>exp magic
> 
> 2017-02-20 17:00:20: <c>exp magic
> 
> 2017-02-20 17:00:44: <c>cast
> 
> 2017-02-20 17:00:51: <c>exp
> 
> 2017-02-20 17:00:54: <c>exp magic
> 
> 2017-02-20 17:00:57: <c>prep stw
> 
> 2017-02-20 17:00:59: <c>cast
> 
> 2017-02-20 17:02:25: <c>exp aug
> 
> 2017-02-20 17:02:35: <c>,kill train
> 
> 2017-02-20 17:02:36: <c>l
> 
> 2017-02-20 17:02:40: <c>l serp
> 
> 2017-02-20 17:02:42: <c>l second serp
> 
> 2017-02-20 17:02:43: <c>cast
> 
> 2017-02-20 17:02:44: <c>l third serp
> 
> 2017-02-20 17:03:00: <c>;narost
> 
> 2017-02-20 17:03:20: <c>;narost
> 
> 2017-02-20 17:03:23: <c>,narost
> 
> 2017-02-20 17:03:28: <c>l
> 
> 2017-02-20 17:03:29: <c>ret
> 
> 2017-02-20 17:03:29: <c>ret
> 
> 2017-02-20 17:03:30: <c>e
> 
> 2017-02-20 17:03:32: <c>e
> 
> 2017-02-20 17:03:34: <c>w
> 
> 2017-02-20 17:03:34: <c>w
> 
> 2017-02-20 17:03:37: <c>e
> 
> 2017-02-20 17:03:40: <c>,go2 ranger
> 
> 2017-02-20 17:03:42: <c>munpause
> 
> 2017-02-20 17:03:44: <c>,unpause
> 
> 2017-02-20 17:03:50: error: server_thread: malformed XML: missing tag start
> Line: 1
> Position: 108
> Last 80 unconsumed characters:
> <streamWindow id='main' title='Story' subtitle=" - ["Hodierna's Grace"]" location
> 	C:/Ruby200/lib/ruby/2.0.0/rexml/parsers/baseparser.rb:372:in `pull_event'
> 	C:/Ruby200/lib/ruby/2.0.0/rexml/parsers/baseparser.rb:183:in `pull'
> 	C:/Ruby200/lib/ruby/2.0.0/rexml/parsers/streamparser.rb:16:in `parse'
> 	C:/Ruby200/lib/ruby/2.0.0/rexml/document.rb:243:in `parse_stream'
> 	lich.rbw:7164:in `block in open'
> 2017-02-20 17:03:50: error: server_thread: malformed XML: missing tag start
> Line: 1
> Position: 135
> Last 80 unconsumed characters:
> <streamWindow id='room' title='Room' subtitle=" - ["Hodierna's Grace"]" location=
> 	C:/Ruby200/lib/ruby/2.0.0/rexml/parsers/baseparser.rb:372:in `pull_event'
> 	C:/Ruby200/lib/ruby/2.0.0/rexml/parsers/baseparser.rb:183:in `pull'
> 	C:/Ruby200/lib/ruby/2.0.0/rexml/parsers/streamparser.rb:16:in `parse'
> 	C:/Ruby200/lib/ruby/2.0.0/rexml/document.rb:243:in `parse_stream'
> 	lich.rbw:7164:in `block in open'
> 2017-02-20 17:06:20: <c>;circle
> 
> 2017-02-20 17:06:22: <c>,circle
> 
> 2017-02-20 17:06:25: <c>exp
> 
> 2017-02-20 17:06:27: <c>l
> 
> 2017-02-20 17:06:32: <c>ask kalika about cirlce
> 
> 2017-02-20 17:06:33: <c>ask kalika about cirlce
> 
> 2017-02-20 17:06:35: <c>ask kalika about circle
> 
> 2017-02-20 17:06:36: <c>ask kalika about circle
> 
> 2017-02-20 17:06:37: <c>ask kalika about circle
> 
> 2017-02-20 17:06:39: <c>ask kalika about circle
> 
> 2017-02-20 17:06:44: <c>exp skill scout
> 
> 2017-02-20 17:06:46: <c>i
> 
> 2017-02-20 17:06:47: <c>l
> 
> 2017-02-20 17:06:49: <c>out
> 
> 2017-02-20 17:06:55: <c>discern stw
> 
> 2017-02-20 17:07:02: <c>prep stw 15
> 
> 2017-02-20 17:07:07: <c>prep stw 15
> 
> 2017-02-20 17:07:08: <c>prep stw 15
> 
> 2017-02-20 17:07:12: <c>;textsubs
> 
> 2017-02-20 17:07:14: <c>,textsubs
> 
> 2017-02-20 17:07:19: <c>l
> 
> 2017-02-20 17:07:30: <c>harness 5
> 
> 2017-02-20 17:07:34: <c>cast
> 
> 2017-02-20 17:07:37: <c>perc
> 
> 2017-02-20 17:07:39: <c>exp
> 
> 2017-02-20 17:07:41: <c>exp aug
> 
> 2017-02-20 17:07:51: <c>disern ey
> 
> 2017-02-20 17:07:52: <c>spell all
> 
> 2017-02-20 17:07:57: <c>discern ey
> 
> 2017-02-20 17:08:04: <c>prep ey 20
> 
> 2017-02-20 17:08:05: <c>prep ey 20
> 
> 2017-02-20 17:08:57: <c>cast
> 
> 2017-02-20 17:09:00: <c>prep ey 15
> 
> 2017-02-20 17:09:54: <c>cast
> 
> 2017-02-20 17:09:57: <c>discern compost
> 
> 2017-02-20 17:12:05: <c>,training
> 
> 2017-02-20 17:15:46: error: server_thread: An existing connection was forcibly closed by the remote host.
> 	lich.rbw:1253:in `write'
> 	lich.rbw:1253:in `puts'
> 	lich.rbw:1253:in `block in puts'
> 	lich.rbw:1252:in `synchronize'
> 	lich.rbw:1252:in `puts'
> 	lich.rbw:7191:in `rescue in block in open'
> 	lich.rbw:7123:in `block in open'
```

**Comment by rcuhljr** [comment]
Should be fixed by [this commit](https://github.com/rcuhljr/dr-lich/commit/a249befac981e048b03784b7f73033e89bb9738b) Let us know if this persists after you've restarted lich twice.

**Comment by intangibles** [comment]
Working great.  Actually feels like it may have removed some of the delay I was feeling when using manual commands and why I didn't notice it during scripts.


I am noticing its saying this after every restart now (restarted 5-6 times), but don't recall if that's the normal message.

[dependency: New version of lich installed, please restart Lich.]
